name: Rust

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check Formatting
      run: cargo fmt --all -- --check
    - name: Check Clippy
      run: cargo clippy -- -D warnings
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install MSYS2, pkg-config, and GLib
      uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-pkg-config
          mingw-w64-x86_64-glib2

    - name: Add MSYS2 to PATH
      run: echo "C:\msys64\mingw64\bin" | Out-File -Append -FilePath $env:GITHUB_PATH

    - name: Build
      run: cargo build --release

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: binary
        path: target/release/video-trimmer.exe

    - name: Upload Resources
      uses: actions/upload-artifact@v4
      with:
        name: resources
        path: static/**
  upload:
    name: Upload new build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/release'
    needs:
      - build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
