name: Rust

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "cache"
        cache-all-crates: true
    - name: Check Formatting
      run: cargo fmt --all -- --check
    - name: Check Clippy
      run: cargo clippy -- -D warnings
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
      with:
        shared-key: "cache"
        cache-all-crates: true
    - name: Build
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Prepare Zip
      run: Compress-Archive -Path "target/x86_64-pc-windows-msvc/release/trimmer-and-thumbnail-gen.exe","static" -DestinationPath trimmer-and-thumbnail-gen.zip

    - name: Upload exe
      uses: actions/upload-artifact@v4
      with:
        name: exe
        path: target/x86_64-pc-windows-msvc/release/trimmer-and-thumbnail-gen.exe

    - name: Upload Zip
      uses: actions/upload-artifact@v4
      with:
        name: trimmer-and-thumbnail-gen
        path: trimmer-and-thumbnail-gen.zip

  upload:
    name: Upload new build
    runs-on: windows-latest
    if: github.ref == 'refs/heads/release'
    needs:
      - build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v5
